### PR TITLE
masp adjustments

### LINKED ISSUE #2722: MASP minor adjustments
The followings should be addressed:

- wrong error message (source not target) https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/namada/src/ledger/native_vp/masp.rs#L353-L356
- Strenghten this check (check that the set is non-empty) https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/namada/src/ledger/native_vp/masp.rs#L326-L329
- Misleading error message https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/namada/src/ledger/native_vp/masp.rs#L328-L329
- Potential overflows:
    - https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/shielded_token/src/conversion.rs#L320-L321
    - https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/shielded_token/src/conversion.rs#L368
    - https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/shielded_token/src/conversion.rs#L283-L286
    - https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/shielded_token/src/conversion.rs#L335C17-L345
- MIsleading comment https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/shielded_token/src/conversion.rs#L289-L297
- Try to share code between https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/namada/src/ledger/native_vp/masp.rs#L342-L406 and https://github.com/anoma/namada/blob/f7532c20072fd877046857f567735770389cd1d0/crates/namada/src/ledger/native_vp/masp.rs#L466-L513

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

closes #2722 - most comments were outdated, only 2 that still applied was checked arithmetic in conversions and inflation overflow warning.

## Indicate on which release or other PRs this topic is based on

0.38.1

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: crates/shielded_token/src/conversion.rs [hunk 1]
```diff
@@ -436,33 +441,39 @@ where
...
                     (token.clone(), denom, digit),
-                    (MaspAmount::from_pair(old_asset, -reward_i128)
-                        + MaspAmount::from_pair(new_asset, reward_i128)
-                        + MaspAmount::from_pair(
-                            reward_assets[digit as usize],
-                            i128::try_from(real_reward)
-                                .into_storage_result()?,
-                        ))
+                    checked!(
+                        MaspAmount::from_pair(old_asset, -precision_i128)
```
Comment (grarco) [inline crates/shielded_token/src/conversion.rs:470]: Should we use the same `checked_neg` we use above?

Comment (tzemanovic) [reply crates/shielded_token/src/conversion.rs:470]: when it's inside `checked!` it gets automatically converted to it by the macro. I haven't done it in the above one cause it's chained with int conversion

**Review by grarco — APPROVED** [review]
