### PR TITLE
Fix IBC amount handling

### LINKED ISSUE #1744: Fix amount handling in IBC transfer
In IBC transfer,
- Need to validate the given amount and the fee
- Fix the conversion from `IbcAmount` to `Amount` for non-native denominations

### PR DESCRIPTION
**Pull request by yito88**
## Describe your changes
Closes #1744 

## Indicate on which release or other PRs this topic is based on
v0.21.1

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: core/src/ledger/ibc/context/common.rs [hunk 1]
```diff
@@ -357,25 +358,96 @@ pub trait IbcCommonContext: IbcStorageContext {
...
+                                "Decoding the token denom failed: Token {}",
+                                token
+                            ),
+                        })
+                    })?;
+                Ok(Some(denom))
+            }
+            None => Ok(None),
+        }
+    }
```
Comment (sug0) [inline core/src/ledger/ibc/context/common.rs:422]: maybe something like this instead?
```rs
Ok(bytes.map(|b| try_from_slice(&b)).transpose()?)
```

File: core/src/ledger/ibc/mod.rs [hunk 2]
```diff
@@ -136,27 +134,47 @@ where
...
+                    .ctx
+                    .borrow()
+                    .get_ibc_event("denomination_trace")
+                    .map_err(|_| {
+                        Error::Denom("Reading the IBC event failed".to_string())
+                    })?;
+                if let Some(event) = result {
+                    if let (Some(trace_hash), Some(ibc_denom)) = (
+                        event.attributes.get("trace_hash"),
+                        event.attributes.get("denom"),
```
Comment (sug0) [inline core/src/ledger/ibc/mod.rs:148]: to avoid writing two chained ifs, you can map and flatten the options
https://doc.rust-lang.org/std/option/enum.Option.html#method.flatten

File: shared/src/ledger/tx.rs [hunk 3]
```diff
@@ -1337,72 +1337,79 @@ pub async fn build_pgf_stewards_proposal<
...
+        client,
+        args.tx.gas_amount,
+        &args.tx.gas_token,
+        args.tx.force,
+    )
+    .await
+    .expect("expected to be able to validate fee");
+
+    args.amount = InputAmount::Validated(validated_amount);
+    args.tx.gas_amount = InputAmount::Validated(validate_fee);
```
Comment (sug0) [inline shared/src/ledger/tx.rs:1370]: I feel like this is unnecessary. can't you use the inner amounts directly?

**Review by sug0 — COMMENTED** [review]
mostly some code style related comments/suggestions

File: shared/src/ledger/tx.rs (hunk 3 above)
Comment (yito88) [reply shared/src/ledger/tx.rs]: You're right. For IBC transfers, we don't have to update them.

**Review by sug0 — APPROVED** [review]
