### PR TITLE
Tune past epochs in storage

### LINKED ISSUE #1783: Need total staked tokens for older governance proposals
Governance proposals may tally voting results at a grace epoch that can be many epochs after the voting end epochs. We currently keep total staked tokens data in the `total_deltas` just for 23 epochs, but this should probably be larger, perhaps some arbitrarily larger number like 100, or some number tied to governance like one related to `max_proposal_period`.

### LINKED ISSUE #1798: Purge more validator information
A follow-up on #1665 to purge some extra information that was overlooked in that PR. In addition to the validator sets themselves, we should be purging the `validator_set_positions` and the LazySet of `validator_addresses` for the same epochs as well.

### LINKED ISSUE #1857: Epochs should be kept for longer in storage
Currently, Namada is only storing up to 2 epochs worth of validator data. This is problematic, as plenty more validator sets are required for validator set updates in the Ethereum bridge.

### LINKED ISSUE #1903: Proposals not being tallied correctly
Thanks to @McDaan , we have realised that `namadac vote-proposal` and `tally_result` are not working as expected.

Currently investigating this issue.

The bug was reported with the following queries:
```
namada client query-proposal-result --proposal-id 0
Proposal Id: 0
    passed with 15002638.990000 yay votes and 0.000000 nay votes (0.%)
```

And after the tally, the result was 

```
namadac query-proposal-result --proposal-id 0
Proposal Id: 0
    rejected with 0.000000 yay votes and 0.000000 nay votes (0.%)
```

Storage after db_dump shows that votes were indeed recorded, but with 0 voting power

```
start_epoch" = "0801000000000000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36gvurqdpjggenvdp4xuuyxvzrgdz52v3exgcrw3fjx5cnws3hgepnqd2xxap5zv6yyef947/#atest1d9khqw36gezrzs6rgdzr2d3sgguyz3p4gcmnzs2rgyuyg3zpxaq5vs33xq6nq32rx4rrxd356g6uud" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36gvurqdpjggenvdp4xuuyxvzrgdz52v3exgcrw3fjx5cnws3hgepnqd2xxap5zv6yyef947/#atest1v4ehgw368ymnzsf5g5u5gv6rxezyxwfhxccnxsengdz5vdesg5mrjvp4xse5xs338ymry33cltfrgt" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36gvurqdpjggenvdp4xuuyxvzrgdz52v3exgcrw3fjx5cnws3hgepnqd2xxap5zv6yyef947/#atest1v4ehgw36ggenqsjpxfpyx3fex5cngvfkgyunzdpcg9zrydejgccrzd3hgvmnzd2xgg6rxd6xy9tr8d" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36gvurqdpjggenvdp4xuuyxvzrgdz52v3exgcrw3fjx5cnws3hgepnqd2xxap5zv6yyef947/#atest1v4ehgw36gvurqdpjggenvdp4xuuyxvzrgdz52v3exgcrw3fjx5cnws3hgepnqd2xxap5zv6yyef947" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36gy6y2dfngccnzsehggu5xsesg56yzv34gdpyzd2rgce5vsehxeryvd2xx56ngwp3l2la94/#atest1v4ehgw36gy6y2dfngccnzsehggu5xsesg56yzv34gdpyzd2rgce5vsehxeryvd2xx56ngwp3l2la94" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36x5cy2v2rxvery329xg6nq33cgfzns33cxsurzv3s89rrwvecx9zrs33nxgunx3pk95ld5f/#atest1v4ehgw36x5cy2v2rxvery329xg6nq33cgfzns33cxsurzv3s89rrwvecx9zrs33nxgunx3pk95ld5f" = "0000"
"#atest1v9hx7w36gahhvetjdeskucm9yqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq5a20qt/proposal/0/vote/#atest1v4ehgw36xeqnvsenxccyz32ygscrz3zygc6y2s6px9znsdecxqurjwp4xy6ngvphg56rjwph8wcvnh/#atest1v4ehgw36xeqnvsenxccyz32ygscrz3zygc6y2s6px9znsdecxqurjwp4xy6ngvphg56rjwph8wcvnh" = "0000"
```

### LINKED ISSUE #1961: Epoched validator protocol key
We should move the validator protocol key into PoS system to make it epoched, so that it can be changed without immediately invalidating txs signed with the original key.

_Originally posted by @sug0 in https://github.com/anoma/namada/pull/1943#discussion_r1342781060_

### PR DESCRIPTION
**Pull request by brentstone**
## Describe your changes
Closes #1798, closes #1857, closes #1903, closes #1783. All of these relate to changing how many past epochs are kept in storage for various PoS data. A refactor is needed to communicate the `max_proposal_period` governance parameter to the data.

Closes #1961. The validator's protocol keys are moved into PoS and now epoched as well.

## Indicate on which release or other PRs this topic is based on
Based on #1943, which is based on v0.23.0

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by brentstone** [comment]
@tzemanovic @Fraccaman @sug0

The PR is ready for a look for anyone who wants to check it out. Here's a summary of the main storage changes:
- `consensus_validator_set` kept for `max_proposal_period + 2` epochs in the past (previously `2`)
- `validator_deltas` kept for `max(max_proposal_period, slash_processing_delay) + 2` epochs in the past (previously `23`)
- `validator_addresses` kept for `2` epochs in the past (previously infinite)
- `validator_positions` kept for `2` epochs in the past (previously infinite)

I've used a `+2` epochs in the past for these things just to err on the side of safety. We can adjust if desired. The `bonds` are already kept for all epochs, so this and the `validator_deltas` should hopefully suffice for governance. At minimum, `validator_deltas` need to be kept for `slash_processing_delay` epochs, hence the `max`.

File: ethereum_bridge/src/protocol/transactions/votes/update.rs [hunk 1]
```diff
@@ -376,6 +377,7 @@ mod tests {
     #[test]
     fn test_apply_duplicate_votes() -> Result<()> {
         let mut wl_storage = TestWlStorage::default();
+        test_utils::init_default_storage(&mut wl_storage);
```
Comment (sug0) [inline ethereum_bridge/src/protocol/transactions/votes/update.rs:380]: I think we never query voting powers from storage in `apply`, so this shouldn't be necessary, unless I'm missing another reason why you've added this here? well, either way, it doesn't hurt to be safe by preemptively initializing storage with  validator data

File: ethereum_bridge/src/protocol/transactions/votes/update.rs [hunk 2]
```diff
@@ -411,6 +413,7 @@ mod tests {
     #[test]
     fn test_calculate_already_seen() -> Result<()> {
         let mut wl_storage = TestWlStorage::default();
+        test_utils::init_default_storage(&mut wl_storage);
```
Comment (sug0) [inline ethereum_bridge/src/protocol/transactions/votes/update.rs:416]: ditto

File: proof_of_stake/src/epoched.rs [hunk 3]
```diff
@@ -269,8 +265,13 @@ where
...
 
-    fn sub_past_epochs(epoch: Epoch) -> Epoch {
-        Epoch(epoch.0.checked_sub(NUM_PAST_EPOCHS).unwrap_or_default())
+    fn sub_past_epochs(params: &PosParams, epoch: Epoch) -> Epoch {
+        Epoch(
+            epoch
+                .0
+                .checked_sub(PastEpochs::value(params))
+                .unwrap_or_default(),
+        )
```
Comment (sug0) [inline proof_of_stake/src/epoched.rs:274]: nit: not really in the scope of this pr I guess, but `Epoch` is a good candidate for a `checked_sub` method, so you don't have to do these destruct-construct gymnastics to subtract a value safely

File: proof_of_stake/src/epoched.rs [hunk 4]
```diff
@@ -367,36 +370,115 @@ where
...
     }
 
-    // pub fn get_inner_by_epoch(&self) -> storage_api::Result<Data> {}
+    /// Update data by removing old epochs
+    /// TODO: should we consider more complex handling of empty epochs in the
+    /// data below?
```
Comment (sug0) [inline proof_of_stake/src/epoched.rs:413]:
```suggestion
    // TODO: should we consider more complex handling of empty epochs in the
    // data below?
```

File: proof_of_stake/src/epoched.rs [hunk 5]
```diff
@@ -367,36 +370,115 @@ where
...
+    ) -> storage_api::Result<()>
+    where
+        S: StorageRead + StorageWrite,
+    {
+        let last_update = self.get_last_update(storage)?;
+        let oldest_epoch = self.get_oldest_epoch(storage)?;
+        println!(
+            "\nLast update = {:?}\nOldest epoch = {:?}\n",
+            last_update, oldest_epoch
+        );
```
Comment (sug0) [inline proof_of_stake/src/epoched.rs:428]:
```suggestion
```
this print should go

File: proof_of_stake/src/epoched.rs [hunk 6]
```diff
@@ -367,36 +370,115 @@ where
...
+                // Go through the epochs before the expected oldest epoch and
+                // keep the latest one
+                tracing::debug!(
+                    "Trimming nested epoched data in epoch {current_epoch}, \
+                     last updated at {last_update}."
+                );
+                let data_handler = self.get_data_handler();
+                // Remove data before the new oldest epoch, keep the latest
+                // value
+                dbg!(&diff);
```
Comment (sug0) [inline proof_of_stake/src/epoched.rs:447]: same deal with the `dbg!()` macro calls.

File: apps/src/lib/node/ledger/shell/finalize_block.rs [hunk 7]
```diff
@@ -100,17 +100,14 @@ where
...
                 current_epoch + pos_params.pipeline_len,
             )?;
             namada_proof_of_stake::store_total_consensus_stake(
                 &mut self.wl_storage,
                 current_epoch,
             )?;
-            namada_proof_of_stake::purge_validator_sets_for_old_epoch(
-                &mut self.wl_storage,
-                current_epoch,
-            )?;
```
Comment (sug0) [inline apps/src/lib/node/ledger/shell/finalize_block.rs:113]: where is the removal taking place now?

**Review by sug0 — CHANGES_REQUESTED** [review]
left some nits & questions, mostly

File: apps/src/lib/node/ledger/shell/finalize_block.rs (hunk 7 above)
Comment (tzemanovic) [reply apps/src/lib/node/ledger/shell/finalize_block.rs:113]: the purges are now done internally in PoS `fn copy_validator_sets_and_positions` (https://github.com/anoma/namada/pull/1944/files#diff-4b7e249d17fe6a121cba4c86bf063ff3f8a57706ae9c56d746ad2ef0058039f2R1556) via calls to `Epoched/EpochedDelta::update_data`

File: ethereum_bridge/src/protocol/transactions/votes/update.rs (hunk 1 above)
Comment (tzemanovic) [reply ethereum_bridge/src/protocol/transactions/votes/update.rs:380]: I think this is needed for the call to `total_consensus_stake_key_handle().set(...` in `TallyParams::setup` that read PoS params

File: apps/src/lib/node/ledger/shell/finalize_block.rs (hunk 7 above)
Comment (sug0) [reply apps/src/lib/node/ledger/shell/finalize_block.rs:113]: gotcha, thx!

File: proof_of_stake/src/epoched.rs (hunk 3 above)
Comment (tzemanovic) [reply proof_of_stake/src/epoched.rs:274]: Yeah, that's shout! We do have `checked_sub` but it takes `Epoch` for right-hand side. We should change it to take `impl Into<Epoch>` to be able to use it with e.g. `u64`

Comment (tzemanovic) [reply proof_of_stake/src/epoched.rs]: I've done this in [2e15d51](https://github.com/anoma/namada/pull/1944/commits/2e15d519604952e54eb365c0e3425df5bbf1f526) and [d3048b3](https://github.com/anoma/namada/pull/1944/commits/d3048b32114920c42a099e1009fb34ed7c6cd19a) - it's a non-breaking change so it's fine to add here imho

**Comment by brentstone** [comment]
pls update wasms

File: proof_of_stake/src/epoched.rs [hunk 8]
```diff
@@ -368,6 +365,100 @@ where
...
+
+    fn sub_past_epochs(params: &PosParams, epoch: Epoch) -> Epoch {
+        epoch
+            .checked_sub(PastEpochs::value(params))
+            .unwrap_or_default()
+    }
+
+    /// Update data by removing old epochs
+    // TODO: should we consider more complex handling of empty epochs in the
+    // data below?
```
Comment (tzemanovic) [inline proof_of_stake/src/epoched.rs:406]: What do you have in mind for this? I think for some `Epoched` types it's common not to have some entry at every past epoch (e.g. `ValidatorConsensusKeys`)

File: proof_of_stake/src/types.rs [hunk 9]
```diff
@@ -141,7 +140,7 @@ pub type ValidatorSlashes = NestedMap<Address, Slashes>;
 pub type EpochedSlashes = crate::epoched::NestedEpoched<
     ValidatorSlashes,
     crate::epoched::OffsetUnbondingLen,
-    crate::epoched::OffsetSlashProcessingLen,
+    crate::epoched::OffsetSlashProcessingLen, /* TODO: should this be slash procesing + cubic window? */
```
Comment (tzemanovic) [inline proof_of_stake/src/types.rs:143]: yeah, we're reading the slashing in cubic window in `fn compute_cubic_slash_rate`

Comment (tzemanovic) [reply proof_of_stake/src/types.rs:143]: ah, it already is that - we're using `params.slash_processing_epoch_offset`

Comment (tzemanovic) [reply proof_of_stake/src/types.rs:143]: I rm'd the comment

File: proof_of_stake/src/epoched.rs (hunk 8 above)
Comment (brentstone) [reply proof_of_stake/src/epoched.rs:406]: Nothing in particular, just wanted to put this note here to revisit what I've implemented if necessary, since there was more complex handling in the non-nested impl. Do you think it's fine as is?

**Review by sug0 — COMMENTED** [review]
deferring the review of this pr until #1943 gets the latest eth key changes

File: proof_of_stake/src/epoched.rs (hunk 8 above)
Comment (tzemanovic) [reply proof_of_stake/src/epoched.rs:406]: I see, in the non-nested impl we set the latest value in case there isn't one at the oldest epoch to keep (`Self::sub_past_epochs`). For all the data where we're currently using `NestedEpoched` we don't need to do this as:
- `ValidatorSetPositions`, `ConsensusValidatorSets`, `BelowCapacityValidatorSets`, `ValidatorAddresses` have a value at every epoch that has not yet been cleared
- enqueued slashes in `EpochedSlashes` will be processed before they're cleared and processed slashes are not epoched

Let's just note this behavior in this rustdoc

**Comment by brentstone** [comment]
@sug0 All the epoch-length changes to the PoS data are being made in this PR, as this is the relevant topic. The eth keys have been changed in 7c7ee029a1e91cd21c41e3c8633a0d4224075b69.

@tzemanovic the enqueued slashes are now manually cleared in 85770beec8bd02d7fb0686611b926192e3c55c81.

File: proof_of_stake/src/types.rs [hunk 10]
```diff
@@ -40,6 +40,13 @@ pub type ValidatorConsensusKeys = crate::epoched::Epoched<
     crate::epoched::OffsetDefaultNumPastEpochs,
 >;
 
+/// Epoched validator's protocol key.
+pub type ValidatorProtocolKeys = crate::epoched::Epoched<
+    common::PublicKey,
+    crate::epoched::OffsetPipelineLen,
+    crate::epoched::OffsetMaxProposalPeriodPlus,
```
Comment (sug0) [inline proof_of_stake/src/types.rs:47]: I think the offset can be reduced in the future. I'm not sure what the appropriate value for this should be, though.

**Review by sug0 — APPROVED** [review]

**Review by tzemanovic — APPROVED** [review]
