### PR TITLE
fix governance proposal execution

### LINKED ISSUE #2884: governance proposals end at the end of the designated Epoch instead of the start
the voting period for a governance proposal is not intuitive

for example, the Shielded Expedition's Prop266 governance proposal was set to run from Epoch 24 to Epoch 28, but didn't end until Epoch 29 started. it's confusing to me, because if i specify that i want a proposal to start at Epoch 24, it should not start at the end of Epoch 24, and so when i specify that i want the proposal to end at Epoch 28, i expect that it should be when Epoch 28 starts.

this should either be updated in the code or in the CLI

### LINKED ISSUE #3081: Drop write log changes on failed governance proposal
https://github.com/anoma/namada/blob/621cce94399e3ce5088e07dfff842f438b216103/crates/apps/src/lib/node/ledger/shell/governance.rs#L367-L387 

Here we match the result of executing the proposals but it looks like we don’t drop the state in the case the execution was not accepted meaning that the changes are kept in the write log. These could be committed later in `finalize_block` leading to the governance proposal being effectively executed even if the actual wasm code was rejected. If instead the next call to `shell.state` is a `drop` instead of a `commit`  then we should be fine but it means that there is some non-determinism based on what the next call will be to the write log will be.

### LINKED ISSUE #3082: Avoid reading wasm code for non-wasm governance proposal
https://github.com/anoma/namada/blob/621cce94399e3ce5088e07dfff842f438b216103/crates/apps/src/lib/node/ledger/shell/governance.rs#L122

Here it looks like we read the proposal code from storage even though we know that the transaction doesn’t have on. Also, we ignore the actual result of the proposal and always log that it was successful

### PR DESCRIPTION
**Pull request by Fraccaman**
## Describe your changes
- Closes #3081 
- Closes #3082 
- Closes #2884

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: crates/namada/src/ledger/governance/mod.rs [hunk 1]
```diff
@@ -81,13 +81,21 @@ where
...
+
         let native_token = self.ctx.pre().get_native_token()?;
 
         // Find the actions applied in the tx
         let actions = self.ctx.read_actions()?;
 
         // There must be at least one action if any of the keys belong to gov
-        if actions.is_empty()
+        if !is_governance_proposal
+            && actions.is_empty()
```
Comment (Fraccaman) [inline crates/namada/src/ledger/governance/mod.rs:98]: @tzemanovic I had to add this condition

**Review by grarco — APPROVED** [review]
Looks good to me! The `proposal_ibc_token_inflation` will keep failing until we fix #3068 so we can ignore it for the time being

**Review by brentstone — APPROVED** [review]
