### PR TITLE
Test batch tx events

### LINKED ISSUE #3397: Wrong `Batch` event
In `handle_inner_tx_results` we set the value for the `Batch` event which is supposed to contain the results of all the inner transactions of the batch. At the moment though, we set its value to be the one of the current inner tx we are evaluating (since `handle_inner_tx_result` is called in a loop for very tx of the batch).

https://github.com/anoma/namada/blob/879a3268f2edfbdd0da1c98cf0e4bbdac48f5b0d/crates/node/src/shell/finalize_block.rs#L494

This means that we are overwriting the value of this event with just the result of the last inner transaction. We should instead read the current value of the event (if present) and extend the `batch_results` field with the new entry.

### PR DESCRIPTION
**Pull request by sug0**
## Describe your changes

Closes #3397

Adds additional test coverage to batch tx events emission, to make sure we correctly build a batch of inner tx events from a batched tx.

## Indicate on which release or other PRs this topic is based on

`v0.39.0`

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: crates/node/src/shell/finalize_block.rs [hunk 1]
```diff
@@ -5796,4 +5796,165 @@ mod test_finalize_block {
...
+                        ),
+                        token: shell.state.in_mem().native_token.clone(),
+                    },
+                    sk.ref_to(),
+                    WRAPPER_GAS_LIMIT.into(),
+                ))));
+            batch.header.chain_id = shell.chain_id.clone();
+            batch.header.atomic = false;
+
+            // append first inner tx to batch (this one is valid)
```
Comment (grarco) [inline crates/node/src/shell/finalize_block.rs:5896]: Nit, we have a `mk_tx_batch` helper for unit tests in `finalize_block` that you could use to build the batch

**Review by grarco — APPROVED** [review]
LGTM, thank you!
