### PR TITLE
Fix ibc-transfer dry-run

### LINKED ISSUE #2730: IBC transfer is accepted, while dry-run is rejected
Executing an IBC transfer in client v0.31.6 with the  `--dry-run` or `--dry-run-wrapper` flags results in a rejection:

`namadac ibc-transfer  --source myaddress --receiver stars1someaddress--token naan --amount 1  --channel-id channel-275 --dry-run`

```Enter your decryption password: 
Dry-run result: Transaction was rejected by VPs: [
  "tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4"
].
Changed key: [
  {
    "segments": [
      {
        "AddressSeg": "tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv"
      },
      {
        "AddressSeg": "tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee"
      },
      {
        "StringSeg": "balance"
      },
      {
        "AddressSeg": "tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4"
      }
    ]
  },
  {
    "segments": [
      {
        "AddressSeg": "tnam1pyqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqej6juv"
      },
      {
        "AddressSeg": "tnam1qxvg64psvhwumv3mwrrjfcz0h3t3274hwggyzcee"
      },
      {
        "StringSeg": "balance"
      },
      {
        "AddressSeg": "tnam1qrqgs5e67esl3yjdq3dccls0470ctcm6m5kx4cal"
      }
    ]
  },
  {
    "segments": [
      {
        "AddressSeg": "tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4"
      },
      {
        "StringSeg": "commitments"
      },
      {
        "StringSeg": "ports"
      },
      {
        "StringSeg": "transfer"
      },
      {
        "StringSeg": "channels"
      },
      {
        "StringSeg": "channel-275"
      },
      {
        "StringSeg": "sequences"
      },
      {
        "StringSeg": "5"
      }
    ]
  },
  {
    "segments": [
      {
        "AddressSeg": "tnam1qcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvtr7x4"
      },
      {
        "StringSeg": "nextSequenceSend"
      },
      {
        "StringSeg": "ports"
      },
      {
        "StringSeg": "transfer"
      },
      {
        "StringSeg": "channels"
      },
      {
        "StringSeg": "channel-275"
      }
    ]
  }
]
```

The same transaction without `--dry-run` is accepted:

`namadac ibc-transfer  --source myaddress --receiver stars1someaddress--token naan --amount 1  --channel-id channel-275`

```Enter your decryption password: 
Transaction added to mempool.
Wrapper transaction hash: 972CFB699DB939A236B5984E0A7DC5A2701F0CD9485AC76A733907C6A492586C
Inner transaction hash: F9979352E76AAD5B2301D6807428AADA9C7170FDE5C2F3441D5C2DA0EDB3D976
Wrapper transaction accepted at height 75053. Used 27 gas.
Waiting for inner transaction result...
Transaction was successfully applied at height 75054. Used 6193 gas.
```

After that transaction, my balance is 3.5 naan lower.

### PR DESCRIPTION
**Pull request by yito88**
## Describe your changes
closes #2730

## Indicate on which release or other PRs this topic is based on
`v0.33.0`

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: crates/ibc/src/context/common.rs [hunk 1]
```diff
@@ -259,11 +259,24 @@ pub trait IbcCommonContext: IbcStorageContext {
...
+                    // become a bit stricter when checking timeouts.
+                    self.get_block_header(height.prev_height())?
+                } else {
+                    None
+                }
             })
-        })?;
+            .ok_or_else(|| {
+                ContextError::from(ClientError::Other {
+                    description: "No host header".to_string(),
```
Comment (tzemanovic) [inline crates/ibc/src/context/common.rs:277]:
```suggestion
                    description: "No host block header".to_string(),
```
(just to be a bit more specific)

**Review by tzemanovic — APPROVED** [review]
