### PR TITLE
tx_ibc wasm again

### LINKED ISSUE #1831: Compiling tx_ibc.wasm on the ledger failed on M1 Mac
When starting the ledger, the pre-compilation for `tx_ibc.wasm` built on my local failed.

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: ImpossibleRelocation(Dynamic(DynamicLabel(0)))
Location: /Users/yuji/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-compiler-singlepass-2.3.0/src/machine_arm64.rs:2064
```

It happened from `v0.21.1`. `v0.21.0` didn't happen. Upgrading `ibc-rs` might cause this issue.

Chip: Apple M1 Pro
OS: macOS 13.2.1

wasm-opt version 114 (version_114)

### PR DESCRIPTION
**Pull request by yito88**
## Describe your changes
Closes #1831 
Revert the workaround for the issue, which is by using the temporary host_env function for IBC.
It still requires floating-point support.

## Indicate on which release or other PRs this topic is based on
`v0.36.1`

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Comment by yito88** [comment]
hmm, it still requires floating-point support. It didn't work after #3209.
```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Shell(LoadingWasm("Invalid WASM using forbidden features: floating-point support is disabled (at offset 0x26fc1). Expected: WasmFeatures { mutable_global: false, saturating_float_to_int: false, si
gn_extension: true, reference_types: false, multi_value: false, bulk_memory: false, simd: false, relaxed_simd: false, threads: false, tail_call: false, floats: false, multi_memory: false, exceptions: false, memory64: false, extended_const: false, comp
onent_model: false, function_references: false, memory_control: false, gc: false }"))
Location: /Users/yuji/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-abci-0.14.0/src/v037/server.rs:179
```

File: crates/tests/src/e2e/ibc_tests.rs [hunk 1]
```diff
@@ -260,28 +260,6 @@ fn run_ledger_ibc_with_hermes() -> Result<()> {
     wait_for_packet_relay(&port_id_a, &channel_id_a, &test_a)?;
     check_balances_after_back(&port_id_b, &channel_id_b, &test_a, &test_b)?;
 
-    // Transfer a token and it will time out and refund
```
Comment (yito88) [inline crates/tests/src/e2e/ibc_tests.rs:263]: This removed test was duplicated

**Review by tzemanovic — DISMISSED** [review]
The changes LGTM, but I think we better investigate and remove the usage of the floats (we can do it as a follow-up). I had a look and some usage comes from tendermint-rs and its use `serde_json` which should be easy to replace by `serde_json_wasm`

File: wasm/tx_ibc/src/lib.rs [hunk 2]
```diff
@@ -7,13 +7,9 @@ use namada_tx_prelude::*;
 
 #[transaction]
 fn apply_tx(ctx: &mut Ctx, tx_data: BatchedTx) -> TxResult {
-    // let data = ctx.get_tx_data(&tx_data)?;
-
-    // let transfer =
-    // ibc::ibc_actions(ctx).execute(&data).into_storage_result()?;
-
-    // Temp. workaround for <https://github.com/anoma/namada/issues/1831>
-    let transfer = tx_ibc_execute()?;
```
Comment (grarco) [inline wasm/tx_ibc/src/lib.rs:16]: Since we are removing the host function can we also remove `crates/benches/txs.rs` and the `allowed_txs` bench entry in `crates/benches/Cargo.toml`? Given that everything runs in wasm now we don't need the benchmarks anymore

Comment (tzemanovic) [reply wasm/tx_ibc/src/lib.rs:16]: done in the last 2 commits

**Review by grarco — APPROVED** [review]
