### PR TITLE
Fix client bug preventing a validator with no self-bonds from voting in governance

### LINKED ISSUE #2865: Problem with voting
Faced with the problem of not being able to vote on behalf of the validator. 
Validator asset from the second era, in the jail was not. 
Example on the vote 266. At the moment voting is available for validators. 

When trying to vote we get an error:
```
namadac vote-proposal --proposal-id 266 --vote yay --address tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
Looking-up public key of tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3 from the ledger...
Error: 
   0: Voter address must have delegations

Location:
   /root/namada/crates/apps/src/lib/cli/client.rs:188
```

The validator address is correct:
```
namadac find-validator --tm-address $(curl -s http://127.0.0.1:26657/status | jq -r '.result.validator_info.address') | grep "Found validator address" | awk -F '"' {'print $2'}
tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
```

Stake is active:

```
namada client bonded-stake | grep tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3
  tnam1qx0pnh3k5f7xvv407wfqteqk8jg52k5s0527lkt3: 28961.000000
```

### PR DESCRIPTION
**Pull request by brentstone**
## Describe your changes
Closes #2865. The client was preventing a validator that has delegations but no self-bonds from submitting a governance proposal vote tx. Now fixed.

## Indicate on which release or other PRs this topic is based on
Based on #2803, which is based on v0.32.0.

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by Fraccaman — DISMISSED** [review]

File: crates/sdk/src/tx.rs [hunk 1]
```diff
@@ -2003,21 +2003,45 @@ pub async fn build_vote_proposal(
...
-    .cloned()
-    .collect::<Vec<Address>>();
-
-    if delegations.is_empty() {
-        return Err(Error::Other(
-            "Voter address must have delegations".to_string(),
-        ));
-    }
+    let delegations = if is_validator {
+        let current_epoch = query_epoch(context.client()).await?;
```
Comment (Fraccaman) [inline crates/sdk/src/tx.rs:2007]: dont need to query for the epoch, can you the one from received in the parameters
