### PR TITLE
fix: do not panic if the user skips the changes

### LINKED ISSUE #1501: Skipping creation of key with the same alias throws error
Assume you have a key in the wallet with alias `aliace`.
Now, if you execute:

`namadaw key gen --alias aliace` 

you will run into the following dialogue: 

```
You're trying to create an alias "aliace" that already exists for a key in your store.
Would you like to replace it? s(k)ip/re(p)lace/re(s)elect: k
```

However, instead of completing this silently (as expected), we receive

```
The application panicked (crashed).
Message:  Action cancelled, no changes persisted.
Location: /Users/unknowit/Heliax/namada/shared/src/ledger/wallet/store.rs:269
```

### PR DESCRIPTION
**Pull request by karbyshev**
Closes #1501

### CODE REVIEW

File: shared/src/ledger/wallet/store.rs [hunk 1]
```diff
@@ -257,24 +259,19 @@ impl Store {
         let (keypair_to_store, raw_keypair) = StoredKeypair::new(sk, password);
         let address = Address::Implicit(ImplicitAddress(pkh.clone()));
         let alias: Alias = alias.unwrap_or_else(|| pkh.clone().into()).into();
-        if self
```
Comment (karbyshev) [inline shared/src/ledger/wallet/store.rs:260]: I think there was a bug here: in the case of alias collision, the user may modify the alias for the keypair, while the originally provided alias have been returned.

Comment (tzemanovic) [reply shared/src/ledger/wallet/store.rs:260]: ah yes, it was not possible to pick a different alias

**Review by tzemanovic — APPROVED** [review]
