### PR TITLE
Fix governance bugs

### LINKED ISSUE #1107: `is_delegator` return `true` for a validator in Gov VP
Inside the governance VP , `fn is_delegator()` will return `true` for a validator with self-bonds, which could unintentionally cause a `true` return value for `is_valid_vote_key`.

File: `shared/src/ledger/native_vp/governance/mod.rs`

### PR DESCRIPTION
**Pull request by grarco**
## Describe your changes

Closes #1107.

Fixes the `is_delegator` function in the governance vp which could return true also for validators with self bonds.
Corrects the inflation mechanism for pgf.

## Indicate on which release or other PRs this topic is based on

Commit 3a0ecd89e8bfea1ca1eda7887d562666674a41d8 on `base` (v0.25.0)

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: apps/src/lib/node/ledger/shell/finalize_block.rs [hunk 1]
```diff
@@ -830,22 +830,23 @@ where
         pgf_fundings.sort_by(|a, b| a.id.cmp(&b.id));
 
         for funding in pgf_fundings {
-            if credit_tokens(
+            if storage_api::token::transfer(
```
Comment (cwgoes) [inline apps/src/lib/node/ledger/shell/finalize_block.rs:833]: I don't think this is complete, we also need to update/change https://github.com/anoma/namada/blob/main/apps/src/lib/node/ledger/shell/finalize_block.rs#L858 - I think we can actually use `credit_tokens` there, but then we shouldn't send the steward inflation to the PGF account in the first place (https://github.com/anoma/namada/blob/main/apps/src/lib/node/ledger/shell/finalize_block.rs#L812)

File: shared/src/ledger/governance/mod.rs [hunk 2]
```diff
@@ -669,21 +669,13 @@ where
         epoch: Epoch,
         verifiers: &BTreeSet<Address>,
         address: &Address,
-        delegation_address: &Address,
+        _delegation_address: &Address,
     ) -> Result<bool> {
-        let bond_handle = pos::namada_proof_of_stake::bond_handle(
+        Ok(pos::namada_proof_of_stake::is_delegator(
```
Comment (Fraccaman) [inline shared/src/ledger/governance/mod.rs:674]: I think we could also add a check if `address != delegation_address`

**Review by cwgoes — APPROVED** [review]
