### PR TITLE
Fix querying error while checking token balance

### LINKED ISSUE #1910: Querying error while checking token balance
By indicating a token symbol or address in `--token` flag on `namadac balance`, it outputs a querying error when there's no balance found. It also contains a typo `Eror`. Shouldn't this querying error be hidden?

By the way, in case there are no balances from any token (i.e. checking balances without `--token` flag), it would be nice to show an output like `No balances found` to avoid confusions. 

```
namadac balance --owner moretest --token NAM
Eror in querying: Querying error: Error in the query: No data found in #atest1v9hx7w36f46kcarfw3hkketwyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpqyqszqgpq4w0mck/#atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5/balance/#atest1d9khqw36g5mr2v6rgsun23zxgg6y2wzzgerryve5xverzvfsg5mnz334xqmrgd3exye5zsfs470s26
No nam balance found for atest1d9khqw36g5mr2v6rgsun23zxgg6y2wzzgerryve5xverzvfsg5mnz334xqmrgd3exye5zsfs470s26
```

### PR DESCRIPTION
**Pull request by sug0**
## Describe your changes

Closes #1910

Supersedes #2089, by rebasing it on `v0.29.0` and squashing irrelevant history.

## Indicate on which release or other PRs this topic is based on

`v0.29.0`

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

**Review by tzemanovic — APPROVED** [review]

File: apps/src/lib/client/rpc.rs [hunk 1]
```diff
@@ -338,8 +340,12 @@ pub async fn query_transparent_balance(
                             balance
                         );
                     }
-                    Err(e) => {
-                        display_line!(context.io(), "Querying error: {e}");
+                    Err(namada_sdk::error::Error::Query(
+                        QueryError::NoSuchKey(_),
+                    )) => {
+                        return;
```
Comment (tzemanovic) [inline apps/src/lib/client/rpc.rs:346]: I think this case should actually print the "No balance found" msg and any other error should still be printed as `edisplay_line!(context.io(), "Querying error: {e}");`

**Review by tzemanovic — APPROVED** [review]
