### PR TITLE
fix node reset

### LINKED ISSUE #1998: Ledger reset does not update CometBFT mode to validator
When we reset the ledger state, despite Namada correctly operating as a validator node, CometBFT operates under the assumption it is connected to a full node.

### PR DESCRIPTION
**Pull request by tzemanovic**
## Describe your changes

closes #1998

## Checklist before merging 
- [ ] If this PR has some consensus breaking changes, I added the corresponding `breaking::` labels
    - This will require 2 reviewers to approve the changes
- [ ] If this PR requires changes to the docs or specs, a corresponding PR is opened in the `namada-docs` repo
    - Relevant PR if applies: 
- [ ] If this PR affects services such as `namada-indexer` or `namada-masp-indexer`, a corresponding PR is opened in that repo
    - Relevant PR if applies:

### CODE REVIEW

File: crates/tests/src/e2e/ledger_tests.rs [hunk 1]
```diff
@@ -342,10 +344,31 @@ fn run_ledger_load_state_and_reset() -> Result<()> {
...
+    // Wait to commit a block again
+    ledger.exp_regex(r"Committed block hash.*, height: [0-9]+")?;
+
+    // 7. Shut it down again
+    ledger.interrupt()?;
+    // Wait for it to stop
+    ledger.exp_eof()?;
+    drop(ledger);
+
+    // 8. Do a full reset the ledger's
```
Comment (sug0) [inline crates/tests/src/e2e/ledger_tests.rs:360]:
```suggestion
    // 8. Do a full reset of the ledger state
```

**Review by sug0 — APPROVED** [review]
