### PR TITLE
Remove `web30` crate and fix Namada interface Ethereum bridge code

### LINKED ISSUE #1506: Fix compatibility with web browser wasm runtimes
Related to https://github.com/anoma/namada/issues/672

Stop depending on `web30`, and any other crate which internally uses `tokio`. We can depend on [`ethers-providers`](https://lib.rs/ethers-providers) instead.

### PR DESCRIPTION
**Pull request by sug0**
Closes #1506 and #672

### CODE REVIEW

File: apps/src/lib/node/ledger/ethereum_oracle/mod.rs [hunk 1]
```diff
@@ -53,12 +47,132 @@ pub enum Error {
...
+impl IntoEthAbiLog for ethers::types::Log {
+    #[inline]
+    fn into_ethabi_log(self) -> ethabi::RawLog {
+        self.into()
+    }
+}
+
+impl IntoEthAbiLog for ethabi::RawLog {
+    #[inline]
+    fn into_ethabi_log(self) -> ethabi::RawLog {
```
Comment (batconjurer) [inline apps/src/lib/node/ledger/ethereum_oracle/mod.rs:66]: Is there a need to make a custom trait here? Rust automatically generates an `impl From<T> for T`
