### PR TITLE
Client improvements

### LINKED ISSUE #3552: Shielding does not automatically reveal a pk
When you attempt to shield with an account whose pk hasn't been revealed yet, the multitoken VP and masp VP both fail with a "signature threshold not met" error.

The returned client message isn't too helpful in figuring out the cause of this error. We should either:

1. Automatically send a reveal pk transaction along with the shielding transaction, or...
2. State the reason of the failure (in this case, the public key hasn't been revealed yet, thus it's missing in storage).

## Example flow

https://pastebin.com/GSRdwyTm

### PR DESCRIPTION
**Pull request by brentstone**
## Describe your changes
- Closes #3552.
- No-op instead of error if a withdraw tx is forced when no unbonds exist.

## Indicate on which release or other PRs this topic is based on
682d7ff

## Checklist before merging to `draft`
- [x] I have added a changelog
- [x] Git history is in acceptable state

### CODE REVIEW

File: crates/proof_of_stake/src/lib.rs [hunk 1]
```diff
@@ -1478,11 +1478,7 @@ where
 
     // Check that there are unbonded tokens available for withdrawal
     if unbond_handle.is_empty(storage)? {
-        return Err(WithdrawError::NoUnbondFound(BondId {
-            source: source.clone(),
-            validator: validator.clone(),
-        })
-        .into());
+        return Ok(token::Amount::zero());
```
Comment (tzemanovic) [inline crates/proof_of_stake/src/lib.rs:1481]: we can also remove the `WithdrawError` now

Comment (brentstone) [reply crates/proof_of_stake/src/lib.rs:1481]: done in 2858dbc7dd285b20d67c4c4d10c99ff2ec87305f

File: crates/apps_lib/src/client/tx.rs [hunk 2]
```diff
@@ -766,18 +766,9 @@ pub async fn submit_transparent_transfer(
...
-        &args
-            .data
-            .first()
-            .ok_or_else(|| {
-                error::Error::Other("Missing transfer data".to_string())
-            })?
-            .source,
-    )
-    .await?;
+    for datum in args.data.iter() {
```
Comment (sug0) [inline crates/apps_lib/src/client/tx.rs:769]: </img>

**Review by sug0 — APPROVED** [review]
lgtm

**Review by tzemanovic — APPROVED** [review]

**Comment by tzemanovic** [comment]
@mergifyio requeue

**Comment by tzemanovic** [comment]
@Mergifyio requeue
